### ISSUE TITLE
https://github.com/XXApple/AndroidLibs

### ISSUE THREAD

**Issue by jp1017** [Mike-bel/awesome-android#1]
Good job. 可否添加这个： :smile: 

https://github.com/XXApple/AndroidLibs

**Comment by Mike-bel** [comment]
哇，这都被你发现啦，果断添加！ @jp1017

**Comment by jp1017** [comment]
:+1: :smiley: 技术鸟很早就关注了，不错哈 :100:

**Comment by Mike-bel** [comment]
谢谢，做这个公众号好久了，交流学习哈 @jp1017
